spring.application.name=schoolevents_api
spring.datasource.url=jdbc:postgresql://dpg-d5rknrkoud1c73en8crg-a.frankfurt-postgres.render.com/schoolevents?sslmode=require
spring.datasource.username=jose
spring.datasource.password=GwpAxiwf9vDhZNanzARQIw4xGHP28NGO
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true